### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-blueprint-reader#4]

**Comment by bnomei** [comment]
yes. simple to do in fact like [a similar plugin proved](https://github.com/AugustMiller/kirby-architect).

**Comment by jenstornell** [comment]
I will probably code it a bit different, but yes, something like that. Keeping it open. =)

**Comment by jenstornell** [comment]
@bnomei Now it has caching as well. Completely rewritten version released.
